# Generated by Django 4.2.7 on 2023-12-11 07:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Mrp', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('Description', tinymce.models.HTMLField()),
                ('Cateroty', models.CharField(choices=[('Attar', 'Attar'), ('Perfume', 'Perfume'), ('Deodent', 'Deodent')], max_length=50)),
                ('Product_Image', models.ImageField(default=None, max_length=300, null=True, upload_to='image/')),
            ],
        ),
    ]
