# Generated by Django 5.0 on 2023-12-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_list_product_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Cateroty',
            new_name='Category',
        ),
    ]
