# Generated by Django 5.0 on 2023-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_cateroty_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(),
        ),
    ]
