# Generated by Django 5.0 on 2023-12-13 07:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=tinymce.models.HTMLField(),
        ),
    ]
