# Generated by Django 5.0 on 2023-12-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
