# Generated by Django 5.0 on 2023-12-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Status',
            field=models.CharField(choices=[('placed', 'placed'), ('packed', 'packed'), ('Shipped', 'Shipped'), ('Out of Delevery', 'Out of Delevery'), ('Delevered', 'Delevered')], default='Pending', max_length=250),
        ),
    ]
