# Generated by Django 5.0 on 2023-12-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_customer_details_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(),
        ),
    ]
