# Generated by Django 5.0.1 on 2024-02-03 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Mobile_Number', models.IntegerField()),
                ('Pincode', models.IntegerField()),
                ('City', models.CharField(max_length=250, null=True)),
                ('Address', models.TextField()),
                ('State', models.CharField(choices=[('Select State', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Amravati', 'Amravati')], default='State', max_length=250)),
                ('Landmark', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250, null=True)),
                ('Mrp', models.FloatField(null=True)),
                ('Selling_Price', models.FloatField(null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Total_Amount', models.FloatField(null=True)),
                ('Product_Image', models.ImageField(default=None, max_length=300, null=True, upload_to='image/')),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Mobile_Number', models.CharField(max_length=12, null=True)),
                ('Pincode', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=250, null=True)),
                ('Address', models.TextField(null=True)),
                ('State', models.CharField(choices=[('Select State', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Amravati', 'Amravati')], default='State', max_length=250, null=True)),
                ('Landmark', models.CharField(max_length=250, null=True)),
                ('OrderDate', models.DateField(default=datetime.date.today, null=True, verbose_name='Date')),
                ('Status', models.CharField(choices=[('placed', 'placed'), ('Shipped', 'Shipped'), ('Out of Delevery', 'Out of Delevery'), ('Delevered', 'Delevered')], default='Placed', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Mrp', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Brand', models.CharField(max_length=250, null=True)),
                ('Category', models.CharField(choices=[('Attar', 'Attar'), ('Perfume', 'Perfume'), ('Deodent', 'Deodent')], max_length=50)),
                ('Stock', models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], max_length=250, null=True)),
                ('Product_Image', models.ImageField(default=None, max_length=300, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_Description', models.TextField()),
                ('image', models.ImageField(default=None, max_length=300, null=True, upload_to='ReviewImages/')),
                ('Date', models.DateField(default=datetime.date.today, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
