# Generated by Django 5.0.1 on 2024-02-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_buy_now'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy_now',
        ),
    ]
