# Generated by Django 5.0.1 on 2024-02-14 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_buy_now'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy_now',
            new_name='Buy_now_model',
        ),
    ]
