# Generated by Django 5.0.1 on 2024-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_buy_now_buy_now_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Order_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Payment_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Razorpay_signature',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
