# Generated by Django 5.0.1 on 2024-02-28 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_orderdetails_prepaid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='Order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='Payment_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='Prepaid',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='Razorpay_signature',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=250)),
                ('Order_id', models.CharField(max_length=250, null=True)),
                ('Payment_id', models.CharField(max_length=250, null=True)),
                ('Razorpay_signature', models.CharField(max_length=250, null=True)),
                ('Prepaid', models.BooleanField(db_default=models.Value(False))),
                ('OrderDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.orderdetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
