# Generated by Django 5.0.1 on 2024-02-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_orderdetails_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='OrderDetails',
        ),
    ]
