# Generated by Django 5.0.1 on 2024-02-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_payment_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.payment'),
        ),
    ]
