# Generated by Django 5.0.1 on 2024-03-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_orderdetails_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='Payment',
        ),
    ]
