# Generated by Django 5.0.1 on 2024-03-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_orderdetails_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.payment'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Out for Delevery', 'Out for Delevery'), ('Delevered', 'Delevered')], default='Placed', max_length=250),
        ),
    ]
