# Generated by Django 5.0.1 on 2024-03-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_orderdetails_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='Payment',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Prepaid',
            field=models.BooleanField(db_default=models.Value(False)),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Razorpay_Order_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Razorpay_Payment_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Razorpay_signature',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
