# Generated by Django 5.0.1 on 2024-03-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_remove_orderdetails_payment_orderdetails_prepaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Razorpay_Order_id',
            field=models.CharField(db_default=models.Value('COD'), max_length=250),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Razorpay_Payment_id',
            field=models.CharField(db_default=models.Value('COD'), max_length=250),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Razorpay_signature',
            field=models.CharField(db_default=models.Value('COD'), max_length=250),
        ),
    ]
